services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports: ["8000:8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
    ports: ["3000:3000"]
    depends_on:
      backend:
        condition: service_healthy
