[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "marketsim"
version = "0.1.0"
requires-python = ">=3.11"
description = "Lightweight market simulator with heterogenous traders"