version: "3.9"
services:
  sim:
    build:
      context: ..
      dockerfile: api/sim_api/Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks: [web]

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [sim]
    networks: [web]

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
